### PR TITLE
Feature/NA61 60 GeV Reweighter 

### PR DESCRIPTION
**Pull request by bmehta4**
This branch is currently working for NOvA experiment only and SVD Decomposition introduced to deal with NA61 data.

### CODE REVIEW

**Comment by bmehta4** [comment]
Thank you very much Mike. I am concerned about one thing, I just viewed it,
as this only works for NOvA we do not have data and simulation files
corresponding to DUNE and other experiments, so is it okay to set all this
into main or should we keep a separate branch till we do not have something
which would work for all the experiments? I just want to make sure I do not
create any troubles.

Thank you
*Bhumika Mehta*
Research Fellow,
Department of Physics,
Panjab University, Chandigarh

**Comment by kordosky** [comment]
Ah. Good catch. I didn't mean to commit it into main. But it won't matter in the short term.  I can try to resolve it in a week or two.

**Comment by bmehta4** [comment]
Sure. Thank you very much. It would be great if we keep a separee branch
till the time a generic one is available. I am working to get DUNE on AL9
work. Once sorted, I will create a generic branch,having all the datasets
(MIPP, AN49, NA61) which will be useful for all the experiments/users.

Thank you
*Bhumika Mehta*
Research Fellow,
Department of Physics,
Panjab University, Chandigarh

**Comment by kordosky** [comment]
You are right. I will need to brush up on my git skills to move the commit to another branch. 

There is something else that I/we need to do. I need to figure out how to retain the backward compatibility of ppfx when new reweighters are added. The issue is that the random number sequence changes. The intent was to have each reweighter have its own random number generator to protect against that problem. But for some reason, we didn't do that. We might have been under time pressure and overlooked it.

**Comment by bmehta4** [comment]
The new reweighter I have added has its own random number generator. It
will not interrupt the NA49 reweighter, so we need not to worry about that.
For retaining the backward compatibility, the issue here is I have replaced
the matrix decomposition method. So the MIPP data won't be used. I intend
to modify it in a way that all the datasets and chosen decomposition
methods can be used. But yes, this branch has NA49 and NA61 datasets, new
decomposition method, all of what we expect to use for NOvA and DUNE
(though MC values for DUNE need to be added for all the datasets).

Thank you
*Bhumika Mehta*
Research Fellow,
Department of Physics,
Panjab University, Chandigarh

**Comment by WilfS** [comment]
@kordosky I also noticed a few unwanted build files were added in the merging of Bhumika's code (CMakeFiles, html etc). I've removed the build files from Bhumika's fork. I think the best way forward to get the nova code on its own branch would be to revert the previous merge-in of Bhumika's code. Next, create a new branch in the ppfx repo called "NOvA_NA61" which is just a copy of the main branch. Then Bhumika can make a pull request with her tidied up code to the NOvA_NA61 branch instead of the main branch.

**Comment by bmehta4** [comment]
Hi Mike,

Happy New Year!
I hope this email finds you well. I am writing to request to accept my
recent pull request and add it as a separate branch. I have made a few
changes, now it will work for both NOvA and DUNE and we will be able to
select the experiment by entering a new variable in the input_script.xml.

I figured some steps to add it as a branch and *undo the changes* that made
us add the previous commit to the main. The steps are as follows:

1) git log (Find the commit hash which lead to addition on ast request to
main branch)
2) git revert <commit_hash>
3) git push origin main

Now, you can add my recent request as a separate branch using
1) git fetch origin pull/<PR_number>/head:<new_branch_name>

This fetches your pull request as a separate branch (<new_branch_name>).

2) git checkout <new_branch_name>
3) git push origin <new_branch_name>

I request you to please accept this at your earliest convenience as we need
to share the version with the other collaborators.
Thanks in anticipation!

Regards
*Bhumika Mehta*
Research Fellow,
Department of Physics,
Panjab University, Chandigarh

**Pull request merged**
